export { default as Aboutme } from './About me/Aboutme'
export { default as Contact } from './Contact/Contact'
export { default as Experience } from './Experience/Experience'
export { default as Footer } from './Footer/Footer'
export { default as Header } from './Header/Header'
export { default as Myservices } from './My Services/Myservices'
export { default as Navigation } from './Navigation/Navigation'
export { default as Portfolio } from './Portfolio/Portfolio'
export { default as Testimonials } from './Testimonials/Testimonials'
